name: Deploy NodeJS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        
    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: '21'
        
    - name: Cache npm dependencies
      uses: actions/cache@v4.1.2
      id: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        npm install
      env:
       NODE_OPTIONS: "--max_old_space_size=4096"
       CI: false

    - name: Build
      run: npm run build
      env:
       VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync to S3
      run: |
        aws s3 sync ./dist/ s3://terminal.dewaldbreed.co.za --delete
        # If your project is built into the 'build' directory. Change it to 'dist' or other directories if applicable.
        # Replace 'your-s3-bucket-name' with your actual bucket name
